### ISSUE TITLE
Cant download data

### ISSUE THREAD

**Issue by ChristianIngwersen** [MingHanLee/GolfPose#1]
Hi wanted to try it out, but the data download link is password protected? :-)

**Comment by MingHanLee** [comment]
The password has been sent to your email. 
Thank you for your attention.

**Comment by sweaterr** [comment]
@MingHanLee Hello, I am also interested in trying this out. Could you please send the password to my email as well? Thank you in advance!

**Comment by MingHanLee** [comment]
Sure, could you please send a request to mhlee.cs09@nycu.edu.tw using your affiliated email address? Thank you

**Comment by sweaterr** [comment]
@MingHanLee Thank you. I sent the request email from my address, sweaterr@gmail.com, yesterday
